# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

pre_install do |installer|
	def installer.verify_no_static_framework_transitive_dependencies; end
end

target 'XCGCrashlyticsLogDestination' do
	use_frameworks!
	
	pod 'XCGLogger'
	pod 'Crashlytics'
	
end
